### ISSUE TITLE
请问验证时的训练、测试的数据怎么定义？能否给出完整示例？

### ISSUE THREAD

**Issue by linh47** [alicogintel/SDM#4]
\SDM-master\code\train\run.py

def run_validating(hparams, model):
    acc_keys = ["user_id", "ds", "user_embedding_output"]

    #  user defined function
    #  you should write your own code here for reading and writing data
    **train_file = get_your_train_files()
    test_file = get_your_test_files()
    writer = open_your_test_result_file()**

不太明白需要什么样的数据格式，是否需要转换，恳请指教。

**Comment by lvfuyu** [comment]
数据是tfrecord格式的，git里传了我们处理过的JD数据集的可以参考。对应的代码这里写的就是数据文件名，比如我们实验环境是从Ali平台某个存储系统里读取的，这里的get_your_train_files()函数对应的就是
![image](https://user-images.githubusercontent.com/4647954/78098874-d9c4ad00-7412-11ea-90de-91a19d2130f3.png)
![image](https://user-images.githubusercontent.com/4647954/78098909-f234c780-7412-11ea-90af-e509bcaa0fe9.png)
