### ISSUE TITLE
num_labels含义

### ISSUE THREAD

**Issue by huzuoliang** [alicogintel/SDM#6]
您好，最近在研究您的sdm源码，有一点疑惑：样例数据中num_labels=5，是把每个session最后的5个item作为目标吗？
![image](https://user-images.githubusercontent.com/45355838/124085869-0d154200-da83-11eb-90d8-75f84d740a03.png)
通过sampled_softmax_loss负采样，inputs=rnn_outputs_split,是用户长短兴趣结合后各个时刻embedding组成的矩阵，那么这边的loss是session中各个时刻都会针对目标num_labels=5进行负采样，然后将所有loss相加？

**Comment by lvfuyu** [comment]
对的

**Comment by huzuoliang** [comment]
谢谢您的回复
